/**
 * Exchanges where Hive is listed on
 */
export const EXCHANGES = [
  {
    id: 'binance',
    name: 'Binance',
    website: 'https://www.binance.com/en/trade/HIVE_USDT',
    image: 'binance.svg',
  },
  // {
  //  id: 'blocktrades',
  //  name: 'Blocktrades',
  //  website: 'https://www.blocktrades.us/en/trade?output_coin_type=hive',
  //  image: 'blocktrades.svg',
  //},
 // {
  //  id: 'beaxy',
  //  name: 'Beaxy',
  //  website: 'https://exchange.beaxy.com/?pair=HIVEBTC',
  //  image: 'beaxy.png',
  // },
  // {
  //  id: 'bitsonic',
  //  name: 'BITSONIC',
  //  website: 'https://bitsonic.co.kr/front/en/exchange/hive-usdt',
  //  image: 'bitsonic.svg',
  //},
  {
    id: 'bittrex',
    name: 'Bittrex',
    website: 'https://bittrex.com/trade/hive-btc',
    image: 'bittrex.svg',
  },
  //{
  //  id: 'bkex',
  //  name: 'BKEX',
  //  website: 'https://www.bkex.com/trade/HIVE_USDT',
  //  image: 'bkex.png',
  //},
  {
    id: 'changelly',
    name: 'Changelly',
    website: 'https://changelly.com',
    image: 'changelly.png',
  },
  {
    id: 'coindcx',
    name: 'CoinDCX',
    website: 'https://coindcx.com/trade/HIVEUSDT',
    image: 'coindcx.svg',
  },
  {
    id: 'coinex',
    name: 'CoinEx',
    website: 'https://www.coinex.com/exchange/hive-usdt',
    image: 'coinex.png',
  },
  {
    id: 'cryptex24',
    name: 'Cryptex24',
    website: 'https://www.cryptex24.io/trade/HIVE&USDT',
    image: 'cryptex24.svg',
  },
  {
    id: 'gateio',
    name: 'gate.io',
    website: 'https://www.gate.io/trade/HIVE_USDT',
    image: 'gateio.svg',
  },
    {
    id: 'easybit',
    name: 'EasyBit',
    website: 'https://easybit.com/en/coin-specs/HIVE',
    image: 'easybit.svg',
  },
 // {
 //   id: 'hbtc',
 //   name: 'HBTC',
 //   website: 'https://www.hbtc.com/exchange/HIVE1/USDT',
 //   image: 'hbtc.png',
 // },
  {
    id: 'hiveengine',
    name: 'Hive Engine',
    website: 'https://hive-engine.com/?p=market&t=SWAP.HIVE',
    image: 'hive-engine.png',
  },
  {
    id: 'huobi',
    name: 'Huobi',
    website: 'https://www.huobi.com/en-us/exchange/hive_usdt/',
    image: 'huobi.svg',
  },
  {
    id: 'ionomy',
    name: 'Ionomy',
    website: 'https://ionomy.com/en/markets/btc-hive',
    image: 'ionomy.png',
  },
    {
    id: 'indodax',
    name: 'Indodax',
    website: 'https://indodax.com/market/HIVEIDR',
    image: 'indodax.png',
  },
  {
    id: 'mandala',
    name: 'Mandala',
    website: 'https://trade.mandala.exchange/en/trade/basic/HIVE_BTC',
    image: 'mandala.png',
  },
  {
    id: 'mexc',
    name: 'MEXC',
    website: 'https://www.mexc.com/exchange/HIVE_USDT?_from=market',
    image: 'mxc.png',
  },
  {
    id: 'probit',
    name: 'ProBit',
    website: 'https://www.probit.com/app/exchange/HIVE-USDT',
    image: 'probit_white.png',
  },
  // {
  //  id: 'routelay',
  //  name: 'Routelay',
  //  website: 'https://routelay.com/?to=hive',
  //  image: 'routelay_white.png',
 // },
 // {
 //   id: 'sequoir',
 //   name: 'Sequoir',
 //   website: 'https://app.sequoir.com/assets/hive',
 //  image: 'sequoir.svg',
 // },
  // {
  //   id: 'steemengine',
  //   name: 'Steem Engine',
  //   website: 'https://steem-engine.net/?p=market&t=HIVEP',
  //   image: 'steem-engine.svg',
  // },
  {
    id: 'sevenb',
    name: 'Seven B',
    website: 'https://sevenb.io',
    image: '7b.png',
  },
  {
    id: 'simpleswap',
    name: 'SimpleSwap',
    website: 'https://simpleswap.io',
    image: 'simpleswap.png',
  },
  {
    id: 'simplex',
    name: 'Simplex',
    website: 'https://www.simplex.com/buy-crypto',
    image: 'simplex.svg',
  },
    {
    id: 'stealthex',
    name: 'StealthEX',
    website: 'https://stealthex.io/coin/hbd',
    image: 'StealthEX.png',
  },
  {
    id: 'swapspace',
    name: 'SwapSpace',
    website: 'https://swapspace.co/?from=btc&to=hive&amount=0.1',
    image: 'swapspace.svg',
  },
  {
    id: 'swapzone',
    name: 'Swapzone',
    website: 'https://swapzone.io/?to=hive',
    image: 'swapzone.svg',
  },
  {
    id: 'upbit',
    name: 'UPbit',
    website: 'https://upbit.com/exchange?code=CRIX.UPBIT.BTC-HIVE',
    image: 'upbit.svg',
  },
  {
    id: 'wazirx',
    name: 'WazirX',
    website: 'https://wazirx.com/exchange/HIVE-USDT',
    image: 'wazirx.png',
  },
    {
    id: 'xbts',
    name: 'XBTS',
    website: 'https://app.xbts.io/#/pools?a=hive',
    image: 'xbts.png',
  }
]
