/**
 * Exchanges where Hive is listed on
 */
export const EXCHANGES = [
  {
    id: 'binance',
    name: 'Binance',
    website: 'https://www.binance.com/en/trade/HIVE_USDT',
    image: 'binance.svg',
  },
  {
    id: 'bitay',
    name: 'Bitay',
    website: 'https://www.bitay.com/t/HIVEUSDT',
    image: 'bitay.png',
  },
  {
    id: 'bithumb',
    name: 'Bithumb',
    website: 'https://www.bithumb.com/react/trade/order/HIVE-KRW',
    image: 'bithumb.png',
  },
  {
    id: 'btcc',
    name: 'BTCC',
    website: 'https://www.btcc.com/en-US/trade/perpetual/HIVEUSDT',
    image: 'btcc.svg',
  },
  {
    id: 'bydfi',
    name: 'Bydfi',
    website: 'https://www.bydfi.com/en/spot/hive_usdt',
    image: 'bydfi.png',
  },
  {
    id: 'changelly',
    name: 'Changelly',
    website: 'https://changelly.com',
    image: 'changelly.png',
  },
  {
    id: 'changenow',
    name: 'ChangeNow',
    website: 'https://changenow.io/?from=hive&to=sol',
    image: 'changenow.png',
  },
  {
    id: 'coindcx',
    name: 'CoinDCX',
    website: 'https://coindcx.com/trade/HIVEUSDT',
    image: 'coindcx.svg',
  },
  {
    id: 'coinex',
    name: 'CoinEx',
    website: 'https://www.coinex.com/exchange/hive-usdt',
    image: 'coinex.png',
  },
  {
    id: 'cryptex24',
    name: 'Cryptex24',
    website: 'https://www.cryptex24.io/trade/HIVE&USDT',
    image: 'cryptex24.svg',
  },
  {
    id: 'digifinex',
    name: 'Digifinex',
    website: 'https://www.digifinex.io/en-ww/trade/USDT/HIVE',
    image: 'digifinex.svg',
  },  
  {
    id: 'easybit',
    name: 'EasyBit',
    website: 'https://easybit.com/en/coin-specs/HIVE',
    image: 'easybit.svg',
  },
  {
    id: 'gateio',
    name: 'gate.io',
    website: 'https://www.gate.io/trade/HIVE_USDT',
    image: 'gateio.svg',
  },
  {
    id: 'hitbtc',
    name: 'HitBTC',
    website: 'https://hitbtc.com/HIVE-to-USDT',
    image: 'hitbtc.png',
  },
  {
    id: 'hiveengine',
    name: 'Hive Engine',
    website: 'https://hive-engine.com/?p=market&t=SWAP.HIVE',
    image: 'hive-engine.png',
  },
  {
    id: 'HTX',
    name: 'HTX',
    website: 'https://www.htx.com/trade/hive_usdt',
    image: 'HTX.svg',
  },
  {
    id: 'ionomy',
    name: 'Ionomy',
    website: 'https://ionomy.com/en/markets/btc-hive',
    image: 'ionomy.png',
  },
  {
    id: 'indodax',
    name: 'Indodax',
    website: 'https://indodax.com/market/HIVEIDR',
    image: 'indodax.png',
  },
  {
    id: 'jucoin',
    name: 'JuCoin',
    website: 'https://www.jbex.com/exchange/HIVE/USDT',
    image: 'jucoin.png',
  },
  {
    id: 'leodex',
    name: 'LeoDex',
    website: 'https://leodex.io/',
    image: 'LeoDex_Logo_no_Name.png',
  },
  {
    id: 'mexc',
    name: 'MEXC',
    website: 'https://www.mexc.com/exchange/HIVE_USDT?_from=market',
    image: 'mxc.png',
  },
  {
    id: 'namiexchange',
    name: 'Nami.Exchange',
    website: 'https://nami.exchange/vi/trade/HIVE-VNST',
    image: 'nami.webp',
  },
  {
    id: 'nominex',
    name: 'Nominex',
    website: 'https://nominex.io/markets/HIVE/USDT',
    image: 'nominex.svg',
  },
  {
    id: 'probit',
    name: 'ProBit',
    website: 'https://www.probit.com/app/exchange/HIVE-USDT',
    image: 'probit_white.png',
  },
  {
    id: 'sevenb',
    name: 'Seven B',
    website: 'https://sevenb.io',
    image: '7b.png',
  },
  {
    id: 'simpleswap',
    name: 'SimpleSwap',
    website: 'https://simpleswap.io',
    image: 'simpleswap.png',
  },
    {
    id: 'stealthex',
    name: 'StealthEX',
    website: 'https://stealthex.io/coin/hbd',
    image: 'StealthEX.png',
  },
  {
    id: 'swapspace',
    name: 'SwapSpace',
    website: 'https://swapspace.co/?from=btc&to=hive&amount=0.1',
    image: 'swapspace.svg',
  },
  {
    id: 'swapzone',
    name: 'Swapzone',
    website: 'https://swapzone.io/?to=hive',
    image: 'swapzone.svg',
  },
  {
    id: 'tokocrypto',
    name: 'Tokocrypto',
    website: 'https://tokocrypto.com/en/trade/HIVE_USDT',
    image: 'tokocrypto.png',
  },
  {
    id: 'upbit',
    name: 'UPbit',
    website: 'https://upbit.com/exchange?code=CRIX.UPBIT.BTC-HIVE',
    image: 'upbit.svg',
  },
  {
    id: 'wazirx',
    name: 'WazirX',
    website: 'https://wazirx.com/exchange/HIVE-USDT',
    image: 'wazirx.png',
  },
  {
    id: 'weex',
    name: 'WEEX',
    website: 'https://www.weex.com/futures/HIVE-USDT',
    image: 'weex.svg',
  },
  {
    id: 'xbts',
    name: 'XBTS',
    website: 'https://app.xbts.io/#/pools?a=hive',
    image: 'xbts.png',
  }
]
